 <?php $form = $this->driverForm; ?>
<div class="title">
	<h3><?php echo $this->pageTitle;?></h3>
	<hr />
</div>
<div class="margin-top20">
	<div class="driver-container">
		<?php echo $this->form()->openTag($form);?>
		<?php echo $this->formRow($form->get('driver_id')); ?>
		<div class="control-group">
			<label class="control-label" for="name">Name</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('name')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="shipper_id">Shipper</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('shipper_id')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="license">License</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('license')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="address1">Address1</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('address1')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="address2">Address2</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('address2')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="cell">Cell</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('cell')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="status">Status</label>
			<div class="controls">
				 <?php echo $this->formRow($form->get('status')); ?>
                </div>
		</div>
		<div class="controls">
            <?php echo $this->formSubmit($form->get('submit')); ?>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<div id="invalid-driver-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-block">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Driver Not Saved!</h4>
			<h5>Please check below shown errors:</h5>
			<div id="driver-errors"></div>
		</div>
	</div>
</div>
<div id="valid-driver-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-success">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Driver saved successfuly</h4>
			<div id="driver-messages">You will now be redirected to driver
				listings.</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$(document).on("submit","#frm_driver",function(e){
		if(!e.isDefaultPrevented()){
			var driverForm = $(this);
			var message = false;
			driverForm.queue(function(next){
				message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while saving driver...");
                    },
                    onBlock:next
                });
			}).queue(function(next){
				$.ajax({
					url : driverForm.attr("action"),
					data : driverForm.serialize(),
					type : "POST",
					dataType : "json",
					success : function(data){
						if(data.response && data.response.success && data.redirect_url){
							$("#valid-driver-template").modal("show");
							setTimeout(function(){
								document.location.href = data.redirect_url;
							},1000);
						} else {
							$("#driver-errors").html(data.response.message);
							$("#invalid-driver-template").modal("show");
						}
					},
					error : function(){
						next();
					} 
				}).complete(next);
			}).queue(function(next){
				message.close();
				next();
			});
			e.preventDefault();
		}
	});
});
</script>