<?php
    $form = $this->loginForm;
    $form->setAttribute('action', $this->url('user', array('controller'=>'login','action' => 'index')));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-signin');
    $form->prepare(); 
?>
<?php echo $this->form()->openTag($form);?>
    <div class="row-fluid">
    
    <img id="logo" src="<?php echo $this->basePath()?>/images/IWS_Logo.png"
		alt="IWS" />
	<h3 class="form-signin-heading">Please sign in</h3>
    <?php
        
        echo $this->formCollection($form);
    ?>
	</div>
<?php echo $this->form()->closeTag();?>
<div id="waiting-template" class="modal hide fade" data-backdrop="static" data-keyboard="false">
    <div class="modal-header">
        <h3>Please Wait...</h3>
    </div>
	<div class="modal-body">
		Please wait while validating your credentials
	</div>
</div>
<div id="invalid-credentials-template" class="modal hide fade">
    <div class="modal-header">
        <h3><i class="icon-remove" style="margin-top:7px"></i>&nbsp;Invalid Credentials</h3>
    </div>
	<div class="modal-body">
		Could not login! Please check <strong>Email-ID</strong>/<strong>Password</strong>
	</div>
	<div class="modal-footer">
        <button class="btn btn-primary" data-dismiss="modal">Ok</button>
    </div>
</div>
<div id="success-template" class="modal hide fade" data-backdrop="static" data-keyboard="false">
    <div class="modal-header">
        <h3><i class="icon-ok" style="margin-top:7px"></i>&nbsp;Login Successful</h3>
    </div>
	<div class="modal-body">
		Please wait while re-directing you to dashbaord...
	</div>
</div>
<script type="text/javascript">
<?php $this->headScript()->captureStart() ?>
(function($){
	$(document).ready(function(){
		$(this).on("submit","#user_login",function(e){
			if(!e.isDefaultPrevented()){
				var loginForm = $(this);
				var message = false;
				var waitingModal = $("#waiting-template");
				var invalidCredentialsModal = $("#invalid-credentials-template");
				var successModal = $("#success-template");
				loginForm.queue(function(next){
					waitingModal.modal("show");
					waitingModal.on("shown",next);
				}).queue(function(next){
					$.ajax({
						url : loginForm.attr("action"),
						data : loginForm.serialize(),
						type : "POST",
						dataType : "json",
						success : function(data){
							if(data.response && data.response.success && data.redirect_url){
								waitingModal.modal("hide");
								waitingModal.on("hidden",function(){
									successModal.modal("show");									
									successModal.on("shown",function(){
										next();
										document.location.href = data.redirect_url;
									});
								});
							} else {
								waitingModal.modal("hide");
								waitingModal.on("hidden",function(){
									invalidCredentialsModal.modal("show");
									invalidCredentialsModal.on("shown",next);
								});
							}
						},
						error : function(){
							waitingModal.modal("hide");
							waitingModal.on("hidden",function(){
								invalidCredentialsModal.modal("show");
								invalidCredentialsModal.on("shown",next);
							});
						}
					});
				});
				e.preventDefault();
			}
		});
	});
})(jQuery);
<?php $this->headScript()->captureEnd() ?>
</script>