 <?php $form = $this->companyForm; ?>
<div class="title">
	<h3><?php echo $this->pageTitle;?></h3>
	<hr />
</div>
<div class="margin-top20 row">
	<div class="company-container">
		<?php echo $this->form()->openTag($form);?>
		<?php echo $this->formRow($form->get('company_id')); ?>
		<div class="span6">
			<div class="control-group">
				<label class="control-label" for="name">Name</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('name')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="address1">Address1</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('address1')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="address2">Address2</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('address2')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="city">City</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('city')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="privision">Provision</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('provision')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="postal_code">Postal Code</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('postal_code')); ?>
			</div>
			</div>
		</div>
		<div class="span6">
			<div class="control-group">
				<label class="control-label" for="phone_office">Phone Office</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('phone_office')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="phone_office_ext">Extension</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('phone_office_ext')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="phone_cell">Phone Cell</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('phone_cell')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="email">Email</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('email')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="rate">Rate</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('rate')); ?>
			</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="status">Status</label>
				<div class="controls">
				<?php echo $this->formRow($form->get('status')); ?>
			</div>
			</div>
		</div>
		<div class="controls text-center">
            <?php echo $this->formSubmit($form->get('submit')); ?>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<div id="invalid-user-add-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-block">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Company Not Saved!</h4>
			<h5>Please check below shown errors:</h5>
			<div id="user-add-errors"></div>
		</div>
	</div>
</div>
<div id="valid-user-add-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-success">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Company saved successfuly</h4>
			<div id="user-add-messages">
				You will now be redirected to company listings.
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$(document).on("submit","#frm_company",function(e){
		if(!e.isDefaultPrevented()){
			var userAddForm = $(this);
			var message = false;
			userAddForm.queue(function(next){
				message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while saving company data...");
                    },
                    onBlock:next
                });
			}).queue(function(next){
				$.ajax({
					url : userAddForm.attr("action"),
					data : userAddForm.serialize(),
					type : "POST",
					dataType : "json",
					success : function(data){
						if(data.response && data.response.success && data.redirect_url){
							$("#valid-user-add-template").modal("show");
							setTimeout(function(){
								document.location.href = data.redirect_url;
							},1000);
						} else {
							$("#user-add-errors").html(data.response.message);
							$("#invalid-user-add-template").modal("show");
						}
					},
					error : function(){
						next();
					} 
				}).complete(next);
			}).queue(function(next){
				message.close();
				next();
			});
			e.preventDefault();
		}
	});
});
</script>