 <?php $form = $this->truckForm; ?>
<div class="title">
	<h3><?php echo $this->pageTitle;?></h3>
	<hr />
</div>
<div class="margin-top20">
	<div class="truck-container">
		<?php echo $this->form()->openTag($form);?>
		<?php echo $this->formRow($form->get('truck_id')); ?>
		<div class="control-group">
			<label class="control-label" for="name">Name</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('name')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="shipper_id">Shipper</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('shipper_id')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="number">Number</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('number')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="make">Make</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('make')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="color">Color</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('color')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="status">Status</label>
			<div class="controls">
				 <?php echo $this->formRow($form->get('status')); ?>
                </div>
		</div>
		<div class="controls">
            <?php echo $this->formSubmit($form->get('submit')); ?>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<div id="invalid-truck-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-block">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Truck Not Saved!</h4>
			<h5>Please check below shown errors:</h5>
			<div id="truck-errors"></div>
		</div>
	</div>
</div>
<div id="valid-truck-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-success">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Truck saved successfuly</h4>
			<div id="truck-messages">You will now be redirected to truck
				listings.</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$(document).on("submit","#frm_truck",function(e){
		if(!e.isDefaultPrevented()){
			var truckForm = $(this);
			var message = false;
			truckForm.queue(function(next){
				message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while saving truck...");
                    },
                    onBlock:next
                });
			}).queue(function(next){
				$.ajax({
					url : truckForm.attr("action"),
					data : truckForm.serialize(),
					type : "POST",
					dataType : "json",
					success : function(data){
						if(data.response && data.response.success && data.redirect_url){
							$("#valid-truck-template").modal("show");
							setTimeout(function(){
								document.location.href = data.redirect_url;
							},1000);
						} else {
							$("#truck-errors").html(data.response.message);
							$("#invalid-truck-template").modal("show");
						}
					},
					error : function(){
						next();
					} 
				}).complete(next);
			}).queue(function(next){
				message.close();
				next();
			});
			e.preventDefault();
		}
	});
});
</script>