<?php $this->headLink()->appendStylesheet($this->basePath() . '/libs/datatables/css/datatables.css')?>
<?php $this->headLink()->appendStylesheet($this->basePath() . '/libs/datatables/css/datatables.bootstrap.css')?>

<?php $this->headScript()->appendFile($this->basePath() . '/libs/datatables/js/datatables.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/libs/datatables/js/datatables.bootstrap.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/libs/datatables/js/datatables.aksplugin.js')?>

<h2>
	Destinaton Addresss <a
		href="<?php echo $this->url("destination-address",array("controller"=>"destination-address","action" => "add"));?>"
		class="btn btn-primary pull-right">Add Destinaton Address</a>
</h2>
<div class="row-fluid margin-top20">
	<div class="span12">
		<table class="table no-delete" id="tblProduct">
			<thead>
				<tr>
					<th>Company</th>
					<th>Description</th>
					<th>Contact</th>
					<th>Address</th>
					<th>Phone</th>
					<th>Licence</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td colspan="7" class="dataTables_empty"><?php echo $this->translate('Loading destination_address list'); ?></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div id="activate-destination_address-template" class="modal hide fade">
	<div class="modal-header">
		<h3>Active DestinatonAddress?</h3>
	</div>
	<div class="modal-body">
		Are you sure you want to activate the destination_address?
		<ul>
			<li>Activating the destination_address will allow you to create new
				transport for the destination_address.</li>
		</ul>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal">Close</button>
		<a href="#" class="continue btn btn-success" data-id="">Continue</a>
	</div>
</div>
<div id="de-activate-destination_address-template"
	class="modal hide fade">
	<div class="modal-header">
		<h3>De-Active DestinatonAddress?</h3>
	</div>
	<div class="modal-body">
		Are you sure you want to de-activate this destination_address?
		<ul>
			<li>No transport can assigned after de-activating a
				destination_address.</li>
			<li>Previous reports of the destination_address can still be visible.</li>
			<li>You can re-activate the destination_address anytime.</li>
		</ul>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal">Close</button>
		<a href="#" class="continue btn btn-danger" data-id="">Continue</a>
	</div>
</div>
<div id="waiting-template" class="modal hide fade"
	data-backdrop="static" data-keyboard="false">
	<div class="modal-header">
		<h3>Please Wait...</h3>
	</div>
	<div class="modal-body">Please wait while changing status of
		destination_address.</div>
</div>
<script type="text/javascript">
<?php $this->headScript()->captureStart()?>
(function($){
	$(document).ready(function(){
		window.grid = dataTable({
			"sDom": "<'row hide'<'span8'l><'span8'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
			"sPaginationType": "bootstrap",
			"oLanguage": {
				"sLengthMenu": "_MENU_ records per page"
			},
			"aoColumns": [
							{ "sName": "company"},
                                                         { "sName": "description"},
							{ "sName": "contact"},
							{ "sName": "address"},
							{ "sName": "phone" },
                                                         { "sName": "licence" },
							{ "sName": "actions",bSortable:false}
						 ],
			id : $('#tblProduct'),
			sAjaxSource: "<?php echo $this->url("destination-address",array("controller"=>"destination-address","action"=>"grid"));?>"
		});
	});
	$(document).on("click",".toggleStatus",function(){
		var self = $(this);
		var isActive = self.attr("data-active");
		var activateDestinatonAddressModal = $("#activate-destination_address-template");
		var deActivateDestinatonAddressModal = $("#de-activate-destination_address-template")
		var id = self.data("id");
		if(isActive == "true"){
			deActivateDestinatonAddressModal.find(".continue").attr("data-id",id);
			deActivateDestinatonAddressModal.modal("show");
		} else {
			activateDestinatonAddressModal.find(".continue").attr("data-id",id);
			activateDestinatonAddressModal.modal("show");
		}
	});
	$(document).on("click",".continue",function(e){
		if(!e.isDefaultPrevented()){
			var self = $(this);
			var destination_address_id = self.attr("data-id");
			var modal = self.closest(".modal");
			var waitingModal = $("#waiting-template");
			self.queue(function(next){
				modal.modal("hide");
				modal.on("hidden",next);
			}).queue(function(next){
				waitingModal.modal("show");
				waitingModal.on("shown",next);
			}).queue(function(next){
				$.ajax({
					url : "<?php echo $this->url('destination-address',array('controller'=>'destination-address','action'=>'toggle-status'));?>",
					data: {destination_address_id:destination_address_id},
					cache:false,
					type: "POST",
					success: function(data){
						if(data.success){
							var targetElement = $(".toggleStatus[data-id="+data.destination_address_id+"]");
							targetElement.html(data.status);
							targetElement.removeClass("btn-danger btn-success").addClass(data["class"]);
							targetElement.attr("data-active",(data.status.toLowerCase() == "active"?"true":"false"));
						}
					}
				}).complete(next);
			}).queue(function(next){
				waitingModal.modal("hide");
				modal.off("hidden");
				waitingModal.off("shown");
				next();
			});
			e.preventDefault();
		}
	});
})(jQuery);
<?php $this->headScript()->captureEnd()?>
</script>