<?php $user = \AfcCommons\StaticOptions\StaticOptions::getCurrentUser();?>
<?php $acl = new \AfcCommons\Permissions\Acl\Acl ( \AfcCommons\Permissions\Acl\Acl::$config ); ?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('Alteration Now Express')->setSeparator(' - ')->setAutoEscape(false)?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>
        <!-- Le styles -->
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/libs/blockui/css/message.css')
            ->prependStylesheet($this->basePath() . '/css/padding-margin.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/libs/bootstrap/css/bootstrap-responsive.min.css')
            ->prependStylesheet($this->basePath() . '/libs/bootstrap/css/bootstrap.min.css')?>

        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            ->prependFile($this->basePath() . '/libs/html5/js/html5.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/libs/blockui/js/message.js')
            ->prependFile($this->basePath() . '/libs/blockui/js/blockui.js')
            ->prependFile($this->basePath() . '/libs/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/libs/jquery/js/jquery-2.0.2.min.js')?>

    </head>
<body>
	<div class="container">
		<div class="container top-center">
			<div id="logo" class="text-center">
				<a href="<?php echo $this->url('home') ?>"><img
					src="<?php echo $this->basePath() . "/img/logo.png"?>"
					alt="Alterations Now Express" /></a>
			</div>
            <?php echo $this->content; ?>
            <hr>
			<!-- <footer>
				<p>&copy; <?php echo date('Y') ?> <?php echo $this->translate('All rights reserved.') ?></p>
			</footer> -->
		</div>
	</div>
	<!-- /container -->
        <?php echo $this->inlineScript()?>
        
    </body>
</html>
