<ul class="breadcrumb">
	<li class="muted"><i>You are at: </i></li>
     <?php
    foreach ( $this->pages as $key => $page ) {
        ?>
                <li>
                    <?php if ($key < count ( $this->pages ) - 1) { ?>
                        <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
                        <span class="divider">/</span>
                    <?php } else { ?>
                        <?php echo '<strong>'.$page->getLabel().'</strong>'; ?>
                    <?php } ?>
                </li>
    <?php } ?>
 </ul>