<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle('IWS : '. $this->translate('Transport Management System'))->setSeparator(' - ')->setAutoEscape(false)?>
<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>
<!-- Le styles -->
<?php
echo $this->headLink ( array ('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath () . '/img/favicon.ico' ) )
    ->prependStylesheet ( $this->basePath () . '/libs/bootstrap/css/bootstrap-responsive.min.css' )
    ->prependStylesheet ( $this->basePath () . '/css/padding-margin.css' )
    ->prependStylesheet ( $this->basePath () . '/css/login.css' )
    ->prependStylesheet ( $this->basePath () . '/libs/bootstrap/css/bootstrap.min.css' )?>
</head>
</head>
<body>
	<div id="wrap">
		<div class="container">
			<?php echo $this->content; ?>
			<hr />
		</div>
		<div id="push"></div>
	</div>
	<div id="footer">
		<div class="container">
			<div class="credit">
				<p class="text-center">&copy; 2012 - <?php echo date('Y') ?> by IWS Enery Group Inc. <?php echo $this->translate('All rights reserved.') ?></p>
                <p class="pull-right hide"><?php echo $this->translate('Powered By: ') ?><a
					target="_blank" href="http://www.atyantik.com"><strong>Atyantik
						Technologies</strong></a></p>
			</div>
		</div>
	</div>
	<!-- /container -->
	<!-- Scripts -->
    <!-- Scripts -->
<?php
echo $this->headScript ()
    ->prependFile ( $this->basePath () . '/libs/html5/js/html5.js', 'text/javascript', array ( 'conditional' => 'lt IE 9' ) )
    ->prependFile ( $this->basePath () . '/libs/bootstrap/js/bootstrap.min.js' )
    ->prependFile ( $this->basePath () . '/libs/jquery/js/jquery-2.0.3.min.js' )
?>
	<?php echo $this->inlineScript()?>
    </body>
</html>
