<h2>Dashboard</h2>
<div class="row-fluid">
	<div class="span12 muted">All the recent activites would be here on the
		dashboard. Example of the future view is shown below:</div>
</div>
<div class="row-fluid">
	<div class="span6">
		<h3>Previous Transaction (Today)</h3>
		<hr />
		<table class="table">
			<thead>
				<tr>
				    <th>Company Name</th>
					<th>Driver</th>
					<th>Start Time</th>
					<th>Reach Time</th>
					<th>Total Weight</th>
				</tr>
			</thead>
			<tbody>
				<tr>
				    <td>BSi Steel Ltd</td>
					<td>Carl</td>
					<td>8:10 AM</td>
					<td>6:10 PM</td>
					<td>80 Tons</td>
				</tr>
				<tr>
				    <td>Portland Cement Company</td>
					<td>Jhonson</td>
					<td>11:10 AM</td>
					<td>15:00 PM</td>
					<td>400 Tons</td>
				</tr>
				<tr>
				    <td>Rhino Cement</td>
					<td>Jonathan</td>
					<td>8:00 AM</td>
					<td>6:10 PM</td>
					<td>20 Tons</td>
				</tr>
				<tr>
				    <td>Example Company</td>
					<td>Aimie</td>
					<td>10:00 AM</td>
					<td>11:35 PM</td>
					<td>50 Tons</td>
				</tr>
				<tr>
				    <td>Mittal Steel</td>
					<td>Richard</td>
					<td>9:18 AM</td>
					<td>12:18 PM</td>
					<td>500 Tons</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="span6">
		<h3>Active Transaction</h3>
		<hr />
		<table class="table">
			<thead>
				<tr>
				    <th>Company Name</th>
					<th>Driver</th>
					<th>Start Time</th>
					<th>Total Weight</th>
				</tr>
			</thead>
			<tbody>
				<tr>
				    <td>BSi Steel Ltd</td>
					<td>Carl</td>
					<td>8:10 AM</td>
					<td>80 Tons</td>
				</tr>
				<tr>
				    <td>Portland Cement Company</td>
					<td>Jhonson</td>
					<td>11:10 AM</td>
					<td>400 Tons</td>
				</tr>
				<tr>
				    <td>Rhino Cement</td>
					<td>Jonathan</td>
					<td>8:00 AM</td>
					<td>20 Tons</td>
				</tr>
				<tr>
				    <td>Example Company</td>
					<td>Aimie</td>
					<td>10:00 AM</td>
					<td>50 Tons</td>
				</tr>
				<tr>
				    <td>Mittal Steel</td>
					<td>Richard</td>
					<td>9:18 AM</td>
					<td>500 Tons</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>