 <?php $form = $this->transportForm; ?>
<div class="title">
	<h3><?php echo $this->pageTitle;?></h3>
	<hr />
</div>
<div class="margin-top20">
	<div class="transport-container">
		<?php echo $this->form()->openTag($form);?>
		<?php echo $this->formRow($form->get('transport_id')); ?>
		<!--div class="control-group">
			<label class="control-label" for="name">Name</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('name')); ?>
			</div>
		</div-->
		<div class="control-group">
			<label class="control-label" for="seller">Seller</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('shipper_id')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="company">Company</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('company_id')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="truck">Truck</label>
			<div class="controls">
				 <?php echo $this->formRow($form->get('truck_id')); ?>
                </div>
		</div>
		<div class="control-group">
			<label class="control-label" for="trailer_id">Trailer</label>
			<div class="controls">
				 <?php echo $this->formRow($form->get('trailer_id')); ?>
                </div>
		</div>
		<div class="control-group">
			<label class="control-label" for="driver">Driver</label>
			<div class="controls">
				 <?php echo $this->formRow($form->get('driver_id')); ?>
                </div>
		</div>
		<div class="control-group">
			<label class="control-label" for="weight">Weight</label>
			<div class="controls">
				 <?php echo $this->formRow($form->get('weight')); ?>
                </div>
		</div>
		<div class="control-group">
			<label class="control-label" for="source_location">Source Location</label>
			<div class="controls">
				 <?php echo $this->formRow($form->get('source_address_id')); ?>
                </div>
		</div>
		<div class="control-group">
			<label class="control-label" for="destination_location">Destination
				Location</label>
			<div class="controls">
				 <?php echo $this->formRow($form->get('destination_address_id')); ?>
                </div>
		</div>
		<div class="controls">
            <?php echo $this->formSubmit($form->get('submit')); ?>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<div id="invalid-transport-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-block">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Transport Not Saved!</h4>
			<h5>Please check below shown errors:</h5>
			<div id="transport-errors"></div>
		</div>
	</div>
</div>
<div id="valid-transport-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-success">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Transport saved successfuly</h4>
			<div id="transport-messages">You will now be redirected to transport
				listings.</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	//$("select[name=destination_address_id] option").remove();
	//$("select[name=destination_address_id]").append("<option> -- Select Destination Address -- </option>");
	$(document).on("change","select[name=company_id]",function(){
		var companyId = $(this);
		var value = parseInt(companyId.val(),10);
		var message = false;
		if(value) {
		companyId.queue(function(next){
			message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while fetching related destination addresses...");
                    },
                    onBlock:next
                });
            
		}).queue(function(next){
				$.ajax({
					url : "<?php echo $this->url('transport',array('controller'=>'transport','action'=>'destination-addresses'));?>",
				data : {'company_id':value},
				type : "POST",
				dataType : "json",
				success : function(data){
					if(data){
						$("select[name=destination_address_id] option").remove();
						$("select[name=destination_address_id]").append("<option value=''> -- Select Destination Address -- </option>");
						$.each(data,function(key,value){
							$("select[name=destination_address_id]").append("<option value='"+key+"'>"+value+"</option>");
							console.log("<option value='"+key+"'>"+value+"</option>");
						});
					}
				},
				error : function(){
					next();
				} 
			}).complete(next);
		}).queue(function(next){
			message.close();
			next();
		});
		} else {
			$("select[name=destination_address_id] options").remove();
			$("select[name=destination_address_id]").append("<option> -- Select Destination Address -- </option>");
		}
	});
	
	// Load Truck/Trailer/Driver By Dharmesh Patel
	/*$("select[name=driver_id] option").remove();
	$("select[name=driver_id]").append("<option value=''> -- Select Driver -- </option>");
	$("select[name=truck_id] option").remove();
	$("select[name=truck_id]").append("<option value=''> -- Select Truck -- </option>");
	$("select[name=trailer_id] option").remove();
	$("select[name=trailer_id]").append("<option value=''> -- Select Trailer -- </option>");*/

	$(document).on("change","select[name=shipper_id]",function(){
		var shipperId = $(this);
		var value = parseInt(shipperId.val(),10);
		var message = false;
		if(value) {
		shipperId.queue(function(next){
			message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while fetching related truck/trailer/driver...");
                    },
                    onBlock:next
                });
            
		}).queue(function(next){
				$.ajax({
					url : "<?php echo $this->url('transport',array('controller'=>'transport','action'=>'fetch-shipper-info'));?>",
				data : {'shipper_id':value},
				type : "POST",
				dataType : "json",
				success : function(data){
					if(data){
						$("select[name=driver_id] option").remove();
						$("select[name=driver_id]").append("<option value=''> -- Select Driver -- </option>");
						$.each(data.driver,function(key,value){
							$("select[name=driver_id]").append("<option value='"+key+"'>"+value+"</option>");
						});
						
						$("select[name=truck_id] option").remove();
						$("select[name=truck_id]").append("<option value='0'> -- Select Truck -- </option>");
						$.each(data.truck,function(key,value){
							$("select[name=truck_id]").append("<option value='"+key+"'>"+value+"</option>");
						});
						
						$("select[name=trailer_id] option").remove();
						$("select[name=trailer_id]").append("<option value='0'> -- Select Trailer -- </option>");
						$.each(data.trailer,function(key,value){
							$("select[name=trailer_id]").append("<option value='"+key+"'>"+value+"</option>");
						});
					}
				},
				error : function(){
					next();
				} 
			}).complete(next);
		}).queue(function(next){
			message.close();
			next();
		});
		} else {
			$("select[name=driver_id] option").remove();
			$("select[name=driver_id]").append("<option value=''> -- Select Driver -- </option>");
			$("select[name=truck_id] option").remove();
			$("select[name=truck_id]").append("<option value=''> -- Select Truck -- </option>");
			$("select[name=trailer_id] option").remove();
			$("select[name=trailer_id]").append("<option value=''> -- Select Trailer -- </option>");
		}
	});
	
	$(document).on("submit","#frm_transport",function(e){
		if(!e.isDefaultPrevented()){
			var transportForm = $(this);
			var message = false;
			transportForm.queue(function(next){
				message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while saving transport...");
                    },
                    onBlock:next
                });
			}).queue(function(next){
				$.ajax({
					url : transportForm.attr("action"),
					data : transportForm.serialize(),
					type : "POST",
					dataType : "json",
					success : function(data){
						if(data.response && data.response.success && data.redirect_url){
							$("#valid-transport-template").modal("show");
							setTimeout(function(){
								document.location.href = data.redirect_url;
							},1000);
						} else {
							$("#transport-errors").html(data.response.message);
							$("#invalid-transport-template").modal("show");
						}
					},
					error : function(){
						next();
					} 
				}).complete(next);
			}).queue(function(next){
				message.close();
				next();
			});
			e.preventDefault();
		}
	});
});
</script>