<?php $this->headLink()->appendStylesheet($this->basePath() . '/libs/datatables/css/datatables.css')?>
<?php $this->headLink()->appendStylesheet($this->basePath() . '/libs/datatables/css/datatables.bootstrap.css')?>

<?php $this->headScript()->appendFile($this->basePath() . '/libs/datatables/js/datatables.min.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/libs/datatables/js/datatables.bootstrap.js')?>
<?php $this->headScript()->appendFile($this->basePath() . '/libs/datatables/js/datatables.aksplugin.js')?>

<h2>
	Transports <a
		href="<?php echo $this->url("transport",array("controller"=>"transport","action" => "add"));?>"
		class="btn btn-primary pull-right">Add Transport</a>
</h2>
<div class="row-fluid margin-top20">
	<div class="span12">
		<table class="table no-delete" id="tblProduct">
			<thead>
				<tr>
					<th>ID</th>
					<!--th>Name</th-->
					<th>Shipper</th>
					<th>Company</th>
					<th>Truck</th>
					<th>Trailer</th>
					<th>Driver</th>
					<th>Source Location</th>
					<th>Destination Location</th>
					<th>Status</th>
					<th>Way Bill</th>
					<th>Invoice</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td colspan="12" class="dataTables_empty"><?php echo $this->translate('Loading transport list'); ?></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div id="activate-transport-template" class="modal hide fade">
	<div class="modal-header">
		<h3>Active Transport?</h3>
	</div>
	<div class="modal-body">
		Are you sure you want to activate the transport?
		<ul>
			<li>Activating the transport will allow you to create new transport
				for the transport.</li>
		</ul>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal">Close</button>
		<a href="#" class="continue btn btn-success" data-id="">Continue</a>
	</div>
</div>
<div id="de-activate-transport-template" class="modal hide fade">
	<div class="modal-header">
		<h3>De-Active Transport?</h3>
	</div>
	<div class="modal-body">
		Are you sure you want to de-activate this transport?
		<ul>
			<li>No transport can assigned after de-activating a transport.</li>
			<li>Previous reports of the transport can still be visible.</li>
			<li>You can re-activate the transport anytime.</li>
		</ul>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal">Close</button>
		<a href="#" class="continue btn btn-danger" data-id="">Continue</a>
	</div>
</div>
<div id="waiting-template" class="modal hide fade"
	data-backdrop="static" data-keyboard="false">
	<div class="modal-header">
		<h3>Please Wait...</h3>
	</div>
	<div class="modal-body">Please wait while changing status of transport.
	</div>
</div>
<script type="text/javascript">
<?php $this->headScript()->captureStart()?>
(function($){
	$(document).ready(function(){
		window.grid = dataTable({
			"sDom": "<'row hide'<'span8'l><'span8'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
			"sPaginationType": "bootstrap",
			"oLanguage": {
				"sLengthMenu": "_MENU_ records per page"
			},
			"aoColumns": [
                            { "sName": "transport_id" },
                            //{ "sName": "name" },
                            { "sName": "shipper_name"},
							{ "sName": "company_name"},
							{ "sName": "truck_name"},
							{ "sName": "plate_number"},
							{ "sName": "driver_name" },
							{ "sName": "source" },
							{ "sName": "destination" },
							{ "sName": "status" },
							{ "sName": "way_bill", bSortable: false },
							{ "sName": "invoice", bSortable: false },
							{ "sName": "actions",bSortable:false}
						 ],
			id : $('#tblProduct'),
			sAjaxSource: "<?php echo $this->url("transport",array("controller"=>"transport","action"=>"grid"));?>"
		});
	});
	$(document).on("click",".toggleStatus",function(){
		var self = $(this);
		var isActive = self.attr("data-active");
		var activateTransportModal = $("#activate-transport-template");
		var deActivateTransportModal = $("#de-activate-transport-template")
		var id = self.data("id");
		if(isActive == "true"){
			deActivateTransportModal.find(".continue").attr("data-id",id);
			deActivateTransportModal.modal("show");
		} else {
			activateTransportModal.find(".continue").attr("data-id",id);
			activateTransportModal.modal("show");
		}
	});
	$(document).on("click",".continue",function(e){
		if(!e.isDefaultPrevented()){
			var self = $(this);
			var transport_id = self.attr("data-id");
			var modal = self.closest(".modal");
			var waitingModal = $("#waiting-template");
			self.queue(function(next){
				modal.modal("hide");
				modal.on("hidden",next);
			}).queue(function(next){
				waitingModal.modal("show");
				waitingModal.on("shown",next);
			}).queue(function(next){
				$.ajax({
					url : "<?php echo $this->url('transport',array('controller'=>'transport','action'=>'toggle-status'));?>",
					data: {transport_id:transport_id},
					cache:false,
					type: "POST",
					success: function(data){
						if(data.success){
							var targetElement = $(".toggleStatus[data-id="+data.transport_id+"]");
							targetElement.html(data.status);
							targetElement.removeClass("btn-warning btn-success").addClass(data["class"]);
							targetElement.attr("data-active",(data.status.toLowerCase() == "active"?"true":"false"));
							
							if(typeof data.invoice != 'undefined') {
								$(".invoice-"+data.transport_id).html(data.invoice);
							} else {
								$(".invoice-"+data.transport_id).html("");
							}
						}
					}
				}).complete(next);
			}).queue(function(next){
				waitingModal.modal("hide");
				modal.off("hidden");
				waitingModal.off("shown");
				next();
			});
			e.preventDefault();
		}
	});
})(jQuery);
<?php $this->headScript()->captureEnd()?>
</script>