<?php $form = $this->trailerForm; ?>
<div class="title">
	<h3><?php echo $this->pageTitle;?></h3>
	<hr />
</div>
<div class="margin-top20">
	<div class="trailer-container">
		<?php echo $this->form()->openTag($form);?>
		<?php echo $this->formRow($form->get('trailer_id')); ?>
		<div class="control-group">
			<label class="control-label" for="shipper_id">Shipper</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('shipper_id')); ?>
			</div>
		</div>
		
		<div class="control-group">
			<label class="control-label" for="plate_number">Plate Number</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('plate_number')); ?>
			</div>
		</div>
		
		<div class="control-group">
			<label class="control-label" for="capacity">Capacity</label>
			<div class="controls">
				<?php echo $this->formRow($form->get('capacity')); ?>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="status">Status</label>
			<div class="controls">
				 <?php echo $this->formRow($form->get('status')); ?>
                </div>
		</div>
		<div class="controls">
            <?php echo $this->formSubmit($form->get('submit')); ?>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>

<div id="invalid-trailer-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-block">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Trailer Not Saved!</h4>
			<h5>Please check below shown errors:</h5>
			<div id="trailer-errors"></div>
		</div>
	</div>
</div>
<div id="valid-trailer-template" class="modal hide fade">
	<div class="modal-body">
		<div class="alert  alert-success">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4>Trailer saved successfuly</h4>
			<div id="trailer-messages">You will now be redirected to trailer
				listings.</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$(document).on("submit","#frm_trailer",function(e){
		if(!e.isDefaultPrevented()){
			var trailerForm = $(this);
			var message = false;
			trailerForm.queue(function(next){
				message = new Message({
                    beforeShow:function (self) {
                        this.alternateMessage = this.showLoadingMessage("Please wait while saving trailer...");
                    },
                    onBlock:next
                });
			}).queue(function(next){
				$.ajax({
					url : trailerForm.attr("action"),
					data : trailerForm.serialize(),
					type : "POST",
					dataType : "json",
					success : function(data){
						if(data.response && data.response.success && data.redirect_url){
							$("#valid-trailer-template").modal("show");
							setTimeout(function(){
								document.location.href = data.redirect_url;
							},1000);
						} else {
							$("#trailer-errors").html(data.response.message);
							$("#invalid-trailer-template").modal("show");
						}
					},
					error : function(){
						next();
					} 
				}).complete(next);
			}).queue(function(next){
				message.close();
				next();
			});
			e.preventDefault();
		}
	});
});
</script>