<form class="form-signin">
	<img id="logo" src="<?php echo $this->basePath()?>/images/IWS_Logo.png" alt="IWS" />
	<h2 class="form-signin-heading">Please sign in</h2>
	<input type="text" class="input-block-level"
		placeholder="Email address"> <input type="password"
		class="input-block-level" placeholder="Password">
	<button class="btn btn-large btn-primary" type="submit">Sign in</button>
</form>
